version: '3'

services:
  app:
    build: ./docker/app
    environment:
      - FRANKENPHP_CONFIG="worker ./public/index.php"
    volumes:
      - './:/app'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db

  db:
    image: 'mysql:latest'
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - 'MYSQL_DATABASE=app'
      - 'MYSQL_ROOT_PASSWORD=secret123'
    volumes:
      - 'app_data:/var/lib/mysql'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'

volumes:
  app_data: ~